#!/usr/bin/env python
"""
Remove the water molecules which have at least one atom in the in Z region specified.

# e.g. The following will remove all SOL solvent molecules which have at least one atom in the Z dimension between coordinates 2 and 6
remove_solatoms.py -f file.gro -o output.gro -b 2 -e 6
# remove all SOL in Z dimension starting from 20 angstroms
remove_solatoms.py -f file.gro -o output.gro -b 20 
# remove all SOL in Z dimension up to 60 angstrom in Z dimension
remove_solatoms.py -f file.gro -o output.gro -e 60
# remove all water
remove_solatoms.py -f file.gro -o output.gro
"""

import argparse
import sys
import os
import MDAnalysis
from collections import Counter

if __name__ == "__main__":
    # argument parser
    argparser = argparse.ArgumentParser(description="Removes the water/sol if any of the atoms reside withing the request Z dimension")
    argparser.add_argument("-f", help="filename .gro from which to remove", metavar="source .gro filename", required=True, type=str)
    argparser.add_argument("-o", help="name of the filename", metavar="output filename", required=True)
    argparser.add_argument("-b", help="start/begin of Z dimension in angstroms", metavar="float", type=float)
    argparser.add_argument("-e", help="end of Z dimension in angstroms", metavar="float", type=float)

    # parse arguments
    args = argparser.parse_args(sys.argv[1:])
    source_filename = args.f
    assert os.path.exists(source_filename), "Argument -f must point to a file"
    output_filename = args.o
    assert '.' in output_filename, 'The output file name has to have an extension that MDAnalysis is capabable of writing, including .gro or .pdb'
    zbegin = args.b if args.b is not None else sys.float_info.min
    zend = args.e if args.e is not None else sys.float_info.max
    assert zbegin < zend, "The first Z dimension value has to be smaller than the second"

    print 'Remove water molecules if any of their atoms reside in Z dim ', zbegin, zend

    u = MDAnalysis.Universe(source_filename)

    # ids of solvent molecules with at least one atom in the Z interval to be excluded
    exile_list_resids_nonuniq = []
    for atom in u.atoms:
        # is solvent?
        if atom.resname != 'SOL':
            continue

        zpos = atom.position[2]
        if zpos > zbegin and zpos < zend:
            exile_list_resids_nonuniq.append(atom.resid)

    # is there a case where more than 3 atoms have the same resids? Because I use a 3-point water model
    resid_counter = Counter(exile_list_resids_nonuniq)
    if any(x > 3 for x in resid_counter.values()):
        print 'More than 3 atoms have the same resid. '
        print "WARNING: ----------------------------------------------"
        print "WARNING: If you are relying on .gro format this opertaion can lead to errors."
        print "WARNING: .gro (and some others) format max ID is 99999 meaning that multiple water molecules"
        print "WARNING: might have the same molecule ID - And this script relies on the uniqueness molecule ID for the removal "
        print "WARNING WORKAROUND: Convert your file first to .crd format (e.g. with MDAnalysis)"
        print "WARNING WORKAROUND: apply the script and then at the end convert your file back to your original format"
        print "WARNING WORKAROUND: .crd requires the IDs to be unique "
        print "WARNING: ----------------------------------------------\n"

    exile_list_resids = set(exile_list_resids_nonuniq)

    if len(exile_list_resids) == 0:
        print 'No molecules to be removed'
        exit(0)

    print 'Number of SOL molecules to be removed: ', len(exile_list_resids)

    # atom indices without the excluded molecules
    # list indexing begins with 0, and atom ids start from 1
    survivors_ids = [atom.id - 1 for atom in u.atoms if atom.resid not in exile_list_resids]
    filtered = u.atoms[survivors_ids]

    if filtered.n_atoms == 0:
        print 'No atoms survived the SOL molecules removal. Exiting.'
        exit(0)

    filtered.write(output_filename)

